### ISSUE TITLE
[Feature] Add Travis CI integration for commit linting

### ISSUE THREAD

**Issue by csshugs** [csshugs/FluidMS#12]
As we now have [commit linting in place](https://github.com/csshugs/FluidMS/pull/10), we should validate this remotely on GitHub as well.

**Comment by fuhlig** [comment]
Those packages might be worth a look:
- [commitlint-config-squash-pr](https://www.npmjs.com/package/commitlint-config-squash-pr) 
- [@commitlint/travis-cli](https://www.npmjs.com/package/@commitlint/travis-cli).

https://www.conventionalcommits.org/en/v1.0.0-beta.2/#do-all-my-contributors-need-to-use-the-conventional-commit-specification

**Comment by csshugs** [comment]
#12 is merged.
