### ISSUE TITLE
[Improvement] Documention: SassDoc

### ISSUE THREAD

**Issue by fuhlig** [csshugs/FluidMS#6]
Utilizing [SassDoc](http://sassdoc.com/), especially mixins and functions can be documentated with annotations:
- examples
- parameter and return values with types and description
- private / public access
...

The documentation can be auto-generated that includes examples, references, requirements etc. ([see SassDoc example for Sass MQ](http://sass-mq.github.io/sass-mq/)).

**Comment by fuhlig** [comment]
https://marketplace.visualstudio.com/items?itemName=rafikis75.vscode-sassdoc

Might be helpful when creating SassDoc comments. Haven't tested it myself and not quite sure if you are on VSCode (yet ;) )

**Comment by csshugs** [comment]
> not quite sure if you are on VSCode

![rolling](https://user-images.githubusercontent.com/4582857/65853782-ed576400-e35a-11e9-90e3-474d1137eb3e.gif)

**Comment by csshugs** [comment]
#8 closes this.
